version: '3.8'
services:

  nginx:
    image: docker.io/overtone1000/nginx_certbot:alpine #docker.io/overtone1000/nginx
    networks:
      - bridge_net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx:/etc/nginx/sites-available/ #certbot will make changes that need to persist
      - static_content:/var/www/html/ #allow static content to persist
      - certbot:/etc/letsencrypt/ #certbot will make changes that need to persist
      - certbot_var:/var/lib/letsencrypt/ #certbot will make changes that need to persist  
    environment:
      CERTBOT_WEBHOOK_PRE: "$CERTBOT_WEBHOOK_PRE" #webhook for certbot pre-renewal
      CERTBOT_WEBHOOK_POST: "$CERTBOT_WEBHOOK_POST" #webhook for certbot post-renewal
      HEALTHCHECK_URL: "$HEALTHCHECK_URL" #webhook for cron heartbeat
      TZ: "US/Los_Angeles"
    logging:
      driver: local
      options:
        max-size: 1m
  
  php:
    image: php:fpm-alpine
    volumes:
      - static_content:/var/www/html/ #php has to be able to access the content? yes, confirmed
    networks:
      - bridge_net
    logging:
      driver: json-file
      options:
        max-size: 1m

volumes:
  cron:
    name: nginx_trm_cron
  nginx:
    name: nginx_trm_nginxconfig
  static_content:
    name: nginx_trm_static_content
  certbot:
    name: nginx_trm_certbot
  certbot_var:
    name: nginx_trm_certbotvar
      
networks:
  bridge_net:
    name: nginx_bridge #can't use the default bridge! DNS using container/service names doesn't work on that.
#    driver: overlay
    attachable: true #allow compose and plain docker containers to attach to this network
